// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLzQWPjBqNzZmd9_u7vQKzK31miJvgww',
    appId: '1:392312646172:web:8fb1eac6f2080754a14dd9',
    messagingSenderId: '392312646172',
    projectId: 'dummy-project-75041',
    authDomain: 'dummy-project-75041.firebaseapp.com',
    storageBucket: 'dummy-project-75041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSCjRV4j4eTdsTVPYF0W-TXE9M3ewbj8',
    appId: '1:392312646172:android:98591d236052cef4a14dd9',
    messagingSenderId: '392312646172',
    projectId: 'dummy-project-75041',
    storageBucket: 'dummy-project-75041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCchp7jnG_xNW90wIURQUlcLc6vntjIGPQ',
    appId: '1:392312646172:ios:846db28cd1e3543ba14dd9',
    messagingSenderId: '392312646172',
    projectId: 'dummy-project-75041',
    storageBucket: 'dummy-project-75041.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCchp7jnG_xNW90wIURQUlcLc6vntjIGPQ',
    appId: '1:392312646172:ios:d2fa77fafe6c4f49a14dd9',
    messagingSenderId: '392312646172',
    projectId: 'dummy-project-75041',
    storageBucket: 'dummy-project-75041.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
